// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'current': string;
  'discount': string;
  'discountCardRequired': string;
  'discountConditions': string;
  'discountPercentage': string;
  'discountText': string;
  'discountUntil': string;
  'expandedGoodCard': string;
  'expandedGoodCardLogo': string;
  'expandedGoodCardMainInfo': string;
  'expandedGoodCardPrices': string;
  'expandedGoodCardSecondaryInfo': string;
  'expandedGoodCardTextWrapper': string;
  'img': string;
  'mobile': string;
  'old': string;
  'pricePerKilo': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'productImage': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'retailer': string;
  'retailerImage': string;
  'retailerText': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
