// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'footerSocialMediaItemSize': string;
  'language': string;
  'languageAll': string;
  'languageCurrent': string;
  'languageCurrentLang': string;
  'languageLang': string;
  'languageLink': string;
  'longText': string;
  'mark': string;
  'mobile': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'rotate': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'shortText': string;
  'shown': string;
  'svg': string;
  'svgImg': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
}
export const cssExports: CssExports;
export default cssExports;
