// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'applyTextMode': string;
  'black': string;
  'blue': string;
  'bubble': string;
  'bubbleArrow': string;
  'desktop': string;
  'disabled': string;
  'green': string;
  'lightblue': string;
  'lightgreen': string;
  'lightorange': string;
  'mobile': string;
  'orange': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'rotate': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
}
export const cssExports: CssExports;
export default cssExports;
