// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centered': string;
  'desktop': string;
  'mobile': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'serviceBlock': string;
  'serviceBlockContent': string;
  'serviceBlockParagraph': string;
  'serviceBlockTitle': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
}
export const cssExports: CssExports;
export default cssExports;
