// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'burger': string;
  'burgerIcon': string;
  'burgerItem': string;
  'burgerMenu': string;
  'burgerMenuBar': string;
  'burgerMenuContent': string;
  'burgerMenuControls': string;
  'burgerMenuItem': string;
  'burgerMenuLink': string;
  'burgerMenuWrapper': string;
  'open': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
}
export const cssExports: CssExports;
export default cssExports;
