// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'desktop': string;
  'fixedBlock': string;
  'mobile': string;
  'open': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'searchBar': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'sideBarHeader': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
