// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blockHeader': string;
  'blockHeaderGoBackBtn': string;
  'desktop': string;
  'justifyCenter': string;
  'mobile': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'removePaddingTop': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'subTitle': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
  'thin': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
