// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'language': string;
  'languageAll': string;
  'languageAllLang': string;
  'languageCurrent': string;
  'languageCurrentLang': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'rotate': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'shown': string;
  'svg': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
}
export const cssExports: CssExports;
export default cssExports;
