// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'info': string;
  'infoText': string;
  'navBar': string;
  'navBarContent': string;
  'navBarControls': string;
  'navBarLangDropdown': string;
  'navBarLogo': string;
  'navBarSearchBar': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'search': string;
  'searchError': string;
  'searchInput': string;
  'searchResults': string;
  'searchResultsItem': string;
  'searchResultsWrapper': string;
  'searchSvg': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'shown': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
}
export const cssExports: CssExports;
export default cssExports;
