// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footerSocialMediaItemSize': string;
  'navBar': string;
  'navBarBurger': string;
  'navBarContent': string;
  'navBarLangDropdown': string;
  'navBarLogo': string;
  'navBarSearchBar': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
}
export const cssExports: CssExports;
export default cssExports;
