// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navBar': string;
  'navBarCenterItem': string;
  'navBarContent': string;
  'navBarLeftItem': string;
  'navBarRightItem': string;
  'navBarSearchBar': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
}
export const cssExports: CssExports;
export default cssExports;
