// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'applyTextMode': string;
  'bg': string;
  'border': string;
  'bubbleArrow': string;
  'bubbleBlack': string;
  'bubbleBlue': string;
  'bubbleDisabled': string;
  'bubbleGreen': string;
  'bubbleLightblue': string;
  'bubbleLightgreen': string;
  'bubbleMobile': string;
  'bubbleMobileActive': string;
  'bubbleOrange': string;
  'bubblelightOrange': string;
  'color': string;
  'cross': string;
  'crossBar': string;
  'one': string;
  'popugYellow': string;
  'popupBlue': string;
  'popupDefault': string;
  'popupGreen': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
  'two': string;
}
export const cssExports: CssExports;
export default cssExports;
