// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'added': string;
  'disabled': string;
  'goodCard': string;
  'goodCardAdd': string;
  'goodCardDiscountUntil': string;
  'goodCardImage': string;
  'goodCardInfo': string;
  'goodCardPricePerKilo': string;
  'goodCardPrices': string;
  'goodCardTextWrapper': string;
  'goodCardTitle': string;
  'info': string;
  'infoDiscount': string;
  'infoMarket': string;
  'prices': string;
  'pricesCurrent': string;
  'pricesOld': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
}
export const cssExports: CssExports;
export default cssExports;
