// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'added': string;
  'current': string;
  'desktop': string;
  'disabled': string;
  'discountUntil': string;
  'goodCard': string;
  'goodCardAdd': string;
  'goodCardImage': string;
  'goodCardInfo': string;
  'goodCardPrices': string;
  'goodCardTextWrapper': string;
  'mobile': string;
  'old': string;
  'pricePerKilo': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'retailerImg': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
