// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'arrowSvg': string;
  'desktop': string;
  'expanded': string;
  'link': string;
  'logoSvg': string;
  'mobile': string;
  'mobileSideBarArrow': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'rotate': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'shown': string;
  'sideBarBoxItem': string;
  'sideBarBoxItemBtn': string;
  'sideBarBoxItemBtnText': string;
  'sideBarBoxItemDropdown': string;
  'sideBarBoxItemDropdownContainer': string;
  'sideBarBoxItemDropdownItem': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
}
export const cssExports: CssExports;
export default cssExports;
