// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'desktop': string;
  'disabled': string;
  'discountText': string;
  'mobile': string;
  'offers': string;
  'primaryColorDark': string;
  'primaryColorLight': string;
  'primaryColorMain': string;
  'quaternaryColorDark': string;
  'quaternaryColorMain': string;
  'retailer': string;
  'retailerCard': string;
  'retailerCardFooter': string;
  'retailerCardHeader': string;
  'retailerImage': string;
  'secondaryColorDark': string;
  'secondaryColorLight': string;
  'secondaryColorMain': string;
  'tertiaryColorDark': string;
  'tertiaryColorLight': string;
  'tertiaryColorMain': string;
}
export const cssExports: CssExports;
export default cssExports;
