// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'desktop': string;
  'mobile': string;
  'retailersCardsBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
